/*
 * generated by Xtext
 */
package org.eclipselabs.spray.shapes;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ShapeRuntimeModule extends org.eclipselabs.spray.shapes.AbstractShapeRuntimeModule {

}
