/*
* generated by Xtext
*/
package org.eclipselabs.spray.shapes.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.eclipselabs.spray.shapes.services.ShapeGrammarAccess;

public class ShapeParser extends AbstractContentAssistParser {
	
	@Inject
	private ShapeGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.eclipselabs.spray.shapes.ui.contentassist.antlr.internal.InternalShapeParser createParser() {
		org.eclipselabs.spray.shapes.ui.contentassist.antlr.internal.InternalShapeParser result = new org.eclipselabs.spray.shapes.ui.contentassist.antlr.internal.InternalShapeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getShapeContainerElementAccess().getAlternatives(), "rule__ShapeContainerElement__Alternatives");
					put(grammarAccess.getAnchorTypeAccess().getAlternatives(), "rule__AnchorType__Alternatives");
					put(grammarAccess.getAnchorPositionPosAccess().getAlternatives(), "rule__AnchorPositionPos__Alternatives");
					put(grammarAccess.getShapeAccess().getAlternatives(), "rule__Shape__Alternatives");
					put(grammarAccess.getShapeConnectionAccess().getAlternatives(), "rule__ShapeConnection__Alternatives");
					put(grammarAccess.getCompartmentShapeAccess().getAlternatives(), "rule__CompartmentShape__Alternatives");
					put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
					put(grammarAccess.getCompartmentLayoutAccess().getAlternatives(), "rule__CompartmentLayout__Alternatives");
					put(grammarAccess.getHAlignAccess().getAlternatives(), "rule__HAlign__Alternatives");
					put(grammarAccess.getVAlignAccess().getAlternatives(), "rule__VAlign__Alternatives");
					put(grammarAccess.getConnectionStyleAccess().getAlternatives(), "rule__ConnectionStyle__Alternatives");
					put(grammarAccess.getAnchorPredefiniedEnumAccess().getAlternatives(), "rule__AnchorPredefiniedEnum__Alternatives");
					put(grammarAccess.getTextTypeAccess().getAlternatives(), "rule__TextType__Alternatives");
					put(grammarAccess.getConnectionDefinitionAccess().getGroup(), "rule__ConnectionDefinition__Group__0");
					put(grammarAccess.getConnectionDefinitionAccess().getGroup_4(), "rule__ConnectionDefinition__Group_4__0");
					put(grammarAccess.getShapeDefinitionAccess().getGroup(), "rule__ShapeDefinition__Group__0");
					put(grammarAccess.getPlacingDefinitionAccess().getGroup(), "rule__PlacingDefinition__Group__0");
					put(grammarAccess.getPlacingDefinitionAccess().getGroup_7(), "rule__PlacingDefinition__Group_7__0");
					put(grammarAccess.getAnchorAccess().getGroup(), "rule__Anchor__Group__0");
					put(grammarAccess.getAnchorManualAccess().getGroup(), "rule__AnchorManual__Group__0");
					put(grammarAccess.getAnchorPositionAccess().getGroup(), "rule__AnchorPosition__Group__0");
					put(grammarAccess.getAnchorRelativePositionAccess().getGroup(), "rule__AnchorRelativePosition__Group__0");
					put(grammarAccess.getAnchorFixPointPositionAccess().getGroup(), "rule__AnchorFixPointPosition__Group__0");
					put(grammarAccess.getCDLineAccess().getGroup(), "rule__CDLine__Group__0");
					put(grammarAccess.getCDLineAccess().getGroup_3(), "rule__CDLine__Group_3__0");
					put(grammarAccess.getCDPolylineAccess().getGroup(), "rule__CDPolyline__Group__0");
					put(grammarAccess.getCDPolylineAccess().getGroup_3(), "rule__CDPolyline__Group_3__0");
					put(grammarAccess.getCDRectangleAccess().getGroup(), "rule__CDRectangle__Group__0");
					put(grammarAccess.getCDRectangleAccess().getGroup_3(), "rule__CDRectangle__Group_3__0");
					put(grammarAccess.getCDRoundedRectangleAccess().getGroup(), "rule__CDRoundedRectangle__Group__0");
					put(grammarAccess.getCDRoundedRectangleAccess().getGroup_3(), "rule__CDRoundedRectangle__Group_3__0");
					put(grammarAccess.getCDPolygonAccess().getGroup(), "rule__CDPolygon__Group__0");
					put(grammarAccess.getCDPolygonAccess().getGroup_3(), "rule__CDPolygon__Group_3__0");
					put(grammarAccess.getCDEllipseAccess().getGroup(), "rule__CDEllipse__Group__0");
					put(grammarAccess.getCDEllipseAccess().getGroup_3(), "rule__CDEllipse__Group_3__0");
					put(grammarAccess.getCDTextAccess().getGroup(), "rule__CDText__Group__0");
					put(grammarAccess.getCDTextAccess().getGroup_3(), "rule__CDText__Group_3__0");
					put(grammarAccess.getLineAccess().getGroup(), "rule__Line__Group__0");
					put(grammarAccess.getLineAccess().getGroup_3(), "rule__Line__Group_3__0");
					put(grammarAccess.getPolylineAccess().getGroup(), "rule__Polyline__Group__0");
					put(grammarAccess.getPolylineAccess().getGroup_3(), "rule__Polyline__Group_3__0");
					put(grammarAccess.getRectangleAccess().getGroup(), "rule__Rectangle__Group__0");
					put(grammarAccess.getRectangleAccess().getGroup_3(), "rule__Rectangle__Group_3__0");
					put(grammarAccess.getRoundedRectangleAccess().getGroup(), "rule__RoundedRectangle__Group__0");
					put(grammarAccess.getRoundedRectangleAccess().getGroup_3(), "rule__RoundedRectangle__Group_3__0");
					put(grammarAccess.getPolygonAccess().getGroup(), "rule__Polygon__Group__0");
					put(grammarAccess.getPolygonAccess().getGroup_3(), "rule__Polygon__Group_3__0");
					put(grammarAccess.getEllipseAccess().getGroup(), "rule__Ellipse__Group__0");
					put(grammarAccess.getEllipseAccess().getGroup_3(), "rule__Ellipse__Group_3__0");
					put(grammarAccess.getTextAccess().getGroup(), "rule__Text__Group__0");
					put(grammarAccess.getTextAccess().getGroup_3(), "rule__Text__Group_3__0");
					put(grammarAccess.getCompartmentInfoAccess().getGroup(), "rule__CompartmentInfo__Group__0");
					put(grammarAccess.getCompartmentInfoAccess().getGroup_2_0(), "rule__CompartmentInfo__Group_2_0__0");
					put(grammarAccess.getCompartmentInfoAccess().getGroup_2_1(), "rule__CompartmentInfo__Group_2_1__0");
					put(grammarAccess.getCompartmentInfoAccess().getGroup_2_2(), "rule__CompartmentInfo__Group_2_2__0");
					put(grammarAccess.getCompartmentInfoAccess().getGroup_2_3(), "rule__CompartmentInfo__Group_2_3__0");
					put(grammarAccess.getCompartmentAccess().getGroup(), "rule__Compartment__Group__0");
					put(grammarAccess.getCompartmentRectangleAccess().getGroup(), "rule__CompartmentRectangle__Group__0");
					put(grammarAccess.getCompartmentRectangleAccess().getGroup_2(), "rule__CompartmentRectangle__Group_2__0");
					put(grammarAccess.getCompartmentRoundedRectangleAccess().getGroup(), "rule__CompartmentRoundedRectangle__Group__0");
					put(grammarAccess.getCompartmentRoundedRectangleAccess().getGroup_2(), "rule__CompartmentRoundedRectangle__Group_2__0");
					put(grammarAccess.getCompartmentPolygonAccess().getGroup(), "rule__CompartmentPolygon__Group__0");
					put(grammarAccess.getCompartmentPolygonAccess().getGroup_2(), "rule__CompartmentPolygon__Group_2__0");
					put(grammarAccess.getCompartmentEllipseAccess().getGroup(), "rule__CompartmentEllipse__Group__0");
					put(grammarAccess.getCompartmentEllipseAccess().getGroup_2(), "rule__CompartmentEllipse__Group_2__0");
					put(grammarAccess.getDescriptionAccess().getGroup(), "rule__Description__Group__0");
					put(grammarAccess.getDescriptionAccess().getGroup_1(), "rule__Description__Group_1__0");
					put(grammarAccess.getDescriptionAccess().getGroup_1_3(), "rule__Description__Group_1_3__0");
					put(grammarAccess.getDescriptionAccess().getGroup_1_3_2(), "rule__Description__Group_1_3_2__0");
					put(grammarAccess.getShapeLayoutAccess().getGroup(), "rule__ShapeLayout__Group__0");
					put(grammarAccess.getShapeLayoutAccess().getGroup_1_0(), "rule__ShapeLayout__Group_1_0__0");
					put(grammarAccess.getShapeLayoutAccess().getGroup_1_1(), "rule__ShapeLayout__Group_1_1__0");
					put(grammarAccess.getShapeLayoutAccess().getGroup_1_2(), "rule__ShapeLayout__Group_1_2__0");
					put(grammarAccess.getShapeLayoutAccess().getGroup_1_3(), "rule__ShapeLayout__Group_1_3__0");
					put(grammarAccess.getRectangleEllipseLayoutAccess().getGroup(), "rule__RectangleEllipseLayout__Group__0");
					put(grammarAccess.getLineLayoutAccess().getGroup(), "rule__LineLayout__Group__0");
					put(grammarAccess.getLineLayoutAccess().getGroup_1(), "rule__LineLayout__Group_1__0");
					put(grammarAccess.getPolyLineLayoutAccess().getGroup(), "rule__PolyLineLayout__Group__0");
					put(grammarAccess.getPolyLineLayoutAccess().getGroup_1(), "rule__PolyLineLayout__Group_1__0");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getGroup(), "rule__RoundedRectangleLayout__Group__0");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getGroup_1_1(), "rule__RoundedRectangleLayout__Group_1_1__0");
					put(grammarAccess.getTextLayoutAccess().getGroup(), "rule__TextLayout__Group__0");
					put(grammarAccess.getTextLayoutAccess().getGroup_1_1(), "rule__TextLayout__Group_1_1__0");
					put(grammarAccess.getTextLayoutAccess().getGroup_1_1_2(), "rule__TextLayout__Group_1_1_2__0");
					put(grammarAccess.getShapestyleLayoutAccess().getGroup(), "rule__ShapestyleLayout__Group__0");
					put(grammarAccess.getShapestyleLayoutAccess().getGroup_1(), "rule__ShapestyleLayout__Group_1__0");
					put(grammarAccess.getShapeStyleRefAccess().getGroup(), "rule__ShapeStyleRef__Group__0");
					put(grammarAccess.getCommonLayoutAccess().getGroup(), "rule__CommonLayout__Group__0");
					put(grammarAccess.getCommonLayoutAccess().getGroup_1_0(), "rule__CommonLayout__Group_1_0__0");
					put(grammarAccess.getCommonLayoutAccess().getGroup_1_1(), "rule__CommonLayout__Group_1_1__0");
					put(grammarAccess.getTextBodyAccess().getGroup(), "rule__TextBody__Group__0");
					put(grammarAccess.getPointAccess().getGroup(), "rule__Point__Group__0");
					put(grammarAccess.getPointAccess().getGroup_1(), "rule__Point__Group_1__0");
					put(grammarAccess.getPointAccess().getGroup_1_9(), "rule__Point__Group_1_9__0");
					put(grammarAccess.getN_INTAccess().getGroup(), "rule__N_INT__Group__0");
					put(grammarAccess.getDOUBLEAccess().getGroup(), "rule__DOUBLE__Group__0");
					put(grammarAccess.getShapeContainerAccess().getShapeContainerElementAssignment(), "rule__ShapeContainer__ShapeContainerElementAssignment");
					put(grammarAccess.getConnectionDefinitionAccess().getNameAssignment_1(), "rule__ConnectionDefinition__NameAssignment_1");
					put(grammarAccess.getConnectionDefinitionAccess().getStyleAssignment_2(), "rule__ConnectionDefinition__StyleAssignment_2");
					put(grammarAccess.getConnectionDefinitionAccess().getConnectionStyleAssignment_4_1(), "rule__ConnectionDefinition__ConnectionStyleAssignment_4_1");
					put(grammarAccess.getConnectionDefinitionAccess().getLayoutAssignment_5(), "rule__ConnectionDefinition__LayoutAssignment_5");
					put(grammarAccess.getConnectionDefinitionAccess().getPlacingAssignment_6(), "rule__ConnectionDefinition__PlacingAssignment_6");
					put(grammarAccess.getShapeDefinitionAccess().getNameAssignment_1(), "rule__ShapeDefinition__NameAssignment_1");
					put(grammarAccess.getShapeDefinitionAccess().getStyleAssignment_2(), "rule__ShapeDefinition__StyleAssignment_2");
					put(grammarAccess.getShapeDefinitionAccess().getShapeLayoutAssignment_4(), "rule__ShapeDefinition__ShapeLayoutAssignment_4");
					put(grammarAccess.getShapeDefinitionAccess().getShapeAssignment_5(), "rule__ShapeDefinition__ShapeAssignment_5");
					put(grammarAccess.getShapeDefinitionAccess().getDescriptionAssignment_6(), "rule__ShapeDefinition__DescriptionAssignment_6");
					put(grammarAccess.getShapeDefinitionAccess().getAnchorAssignment_7(), "rule__ShapeDefinition__AnchorAssignment_7");
					put(grammarAccess.getPlacingDefinitionAccess().getOffsetAssignment_6(), "rule__PlacingDefinition__OffsetAssignment_6");
					put(grammarAccess.getPlacingDefinitionAccess().getDistanceAssignment_7_3(), "rule__PlacingDefinition__DistanceAssignment_7_3");
					put(grammarAccess.getPlacingDefinitionAccess().getAngleAssignment_7_7(), "rule__PlacingDefinition__AngleAssignment_7_7");
					put(grammarAccess.getPlacingDefinitionAccess().getShapeConAssignment_9(), "rule__PlacingDefinition__ShapeConAssignment_9");
					put(grammarAccess.getAnchorAccess().getTypeAssignment_1(), "rule__Anchor__TypeAssignment_1");
					put(grammarAccess.getAnchorPredefiniedAccess().getValueAssignment(), "rule__AnchorPredefinied__ValueAssignment");
					put(grammarAccess.getAnchorManualAccess().getPositionAssignment_1(), "rule__AnchorManual__PositionAssignment_1");
					put(grammarAccess.getAnchorPositionAccess().getPosAssignment_2(), "rule__AnchorPosition__PosAssignment_2");
					put(grammarAccess.getAnchorRelativePositionAccess().getXoffsetAssignment_2(), "rule__AnchorRelativePosition__XoffsetAssignment_2");
					put(grammarAccess.getAnchorRelativePositionAccess().getYoffsetAssignment_6(), "rule__AnchorRelativePosition__YoffsetAssignment_6");
					put(grammarAccess.getAnchorFixPointPositionAccess().getXcorAssignment_2(), "rule__AnchorFixPointPosition__XcorAssignment_2");
					put(grammarAccess.getAnchorFixPointPositionAccess().getYcorAssignment_6(), "rule__AnchorFixPointPosition__YcorAssignment_6");
					put(grammarAccess.getCDLineAccess().getStyleAssignment_2(), "rule__CDLine__StyleAssignment_2");
					put(grammarAccess.getCDLineAccess().getLayoutAssignment_3_1(), "rule__CDLine__LayoutAssignment_3_1");
					put(grammarAccess.getCDPolylineAccess().getStyleAssignment_2(), "rule__CDPolyline__StyleAssignment_2");
					put(grammarAccess.getCDPolylineAccess().getLayoutAssignment_3_1(), "rule__CDPolyline__LayoutAssignment_3_1");
					put(grammarAccess.getCDRectangleAccess().getStyleAssignment_2(), "rule__CDRectangle__StyleAssignment_2");
					put(grammarAccess.getCDRectangleAccess().getLayoutAssignment_3_1(), "rule__CDRectangle__LayoutAssignment_3_1");
					put(grammarAccess.getCDRoundedRectangleAccess().getStyleAssignment_2(), "rule__CDRoundedRectangle__StyleAssignment_2");
					put(grammarAccess.getCDRoundedRectangleAccess().getLayoutAssignment_3_1(), "rule__CDRoundedRectangle__LayoutAssignment_3_1");
					put(grammarAccess.getCDPolygonAccess().getStyleAssignment_2(), "rule__CDPolygon__StyleAssignment_2");
					put(grammarAccess.getCDPolygonAccess().getLayoutAssignment_3_1(), "rule__CDPolygon__LayoutAssignment_3_1");
					put(grammarAccess.getCDEllipseAccess().getStyleAssignment_2(), "rule__CDEllipse__StyleAssignment_2");
					put(grammarAccess.getCDEllipseAccess().getLayoutAssignment_3_1(), "rule__CDEllipse__LayoutAssignment_3_1");
					put(grammarAccess.getCDTextAccess().getTexttypeAssignment_1(), "rule__CDText__TexttypeAssignment_1");
					put(grammarAccess.getCDTextAccess().getStyleAssignment_2(), "rule__CDText__StyleAssignment_2");
					put(grammarAccess.getCDTextAccess().getLayoutAssignment_3_1(), "rule__CDText__LayoutAssignment_3_1");
					put(grammarAccess.getCDTextAccess().getBodyAssignment_3_2(), "rule__CDText__BodyAssignment_3_2");
					put(grammarAccess.getLineAccess().getStyleAssignment_2(), "rule__Line__StyleAssignment_2");
					put(grammarAccess.getLineAccess().getLayoutAssignment_3_1(), "rule__Line__LayoutAssignment_3_1");
					put(grammarAccess.getPolylineAccess().getStyleAssignment_2(), "rule__Polyline__StyleAssignment_2");
					put(grammarAccess.getPolylineAccess().getLayoutAssignment_3_1(), "rule__Polyline__LayoutAssignment_3_1");
					put(grammarAccess.getRectangleAccess().getStyleAssignment_2(), "rule__Rectangle__StyleAssignment_2");
					put(grammarAccess.getRectangleAccess().getCompartmentInfoAssignment_3_1(), "rule__Rectangle__CompartmentInfoAssignment_3_1");
					put(grammarAccess.getRectangleAccess().getLayoutAssignment_3_2(), "rule__Rectangle__LayoutAssignment_3_2");
					put(grammarAccess.getRectangleAccess().getShapeAssignment_3_3(), "rule__Rectangle__ShapeAssignment_3_3");
					put(grammarAccess.getRoundedRectangleAccess().getStyleAssignment_2(), "rule__RoundedRectangle__StyleAssignment_2");
					put(grammarAccess.getRoundedRectangleAccess().getLayoutAssignment_3_1(), "rule__RoundedRectangle__LayoutAssignment_3_1");
					put(grammarAccess.getRoundedRectangleAccess().getShapeAssignment_3_2(), "rule__RoundedRectangle__ShapeAssignment_3_2");
					put(grammarAccess.getPolygonAccess().getStyleAssignment_2(), "rule__Polygon__StyleAssignment_2");
					put(grammarAccess.getPolygonAccess().getLayoutAssignment_3_1(), "rule__Polygon__LayoutAssignment_3_1");
					put(grammarAccess.getPolygonAccess().getShapeAssignment_3_2(), "rule__Polygon__ShapeAssignment_3_2");
					put(grammarAccess.getEllipseAccess().getStyleAssignment_2(), "rule__Ellipse__StyleAssignment_2");
					put(grammarAccess.getEllipseAccess().getCompartmentInfoAssignment_3_1(), "rule__Ellipse__CompartmentInfoAssignment_3_1");
					put(grammarAccess.getEllipseAccess().getLayoutAssignment_3_2(), "rule__Ellipse__LayoutAssignment_3_2");
					put(grammarAccess.getEllipseAccess().getShapeAssignment_3_3(), "rule__Ellipse__ShapeAssignment_3_3");
					put(grammarAccess.getTextAccess().getTexttypeAssignment_1(), "rule__Text__TexttypeAssignment_1");
					put(grammarAccess.getTextAccess().getStyleAssignment_2(), "rule__Text__StyleAssignment_2");
					put(grammarAccess.getTextAccess().getLayoutAssignment_3_1(), "rule__Text__LayoutAssignment_3_1");
					put(grammarAccess.getTextAccess().getBodyAssignment_3_2(), "rule__Text__BodyAssignment_3_2");
					put(grammarAccess.getCompartmentInfoAccess().getCompartmentLayoutAssignment_2_0_2(), "rule__CompartmentInfo__CompartmentLayoutAssignment_2_0_2");
					put(grammarAccess.getCompartmentInfoAccess().getStretchHAssignment_2_1_4(), "rule__CompartmentInfo__StretchHAssignment_2_1_4");
					put(grammarAccess.getCompartmentInfoAccess().getStretchVAssignment_2_1_8(), "rule__CompartmentInfo__StretchVAssignment_2_1_8");
					put(grammarAccess.getCompartmentInfoAccess().getSpacingAssignment_2_2_2(), "rule__CompartmentInfo__SpacingAssignment_2_2_2");
					put(grammarAccess.getCompartmentInfoAccess().getMarginAssignment_2_3_2(), "rule__CompartmentInfo__MarginAssignment_2_3_2");
					put(grammarAccess.getCompartmentInfoAccess().getInvisibleAssignment_2_4(), "rule__CompartmentInfo__InvisibleAssignment_2_4");
					put(grammarAccess.getCompartmentInfoAccess().getIdAssignment_2_5(), "rule__CompartmentInfo__IdAssignment_2_5");
					put(grammarAccess.getCompartmentAccess().getCompartmentLayoutAssignment_2(), "rule__Compartment__CompartmentLayoutAssignment_2");
					put(grammarAccess.getCompartmentAccess().getShapeAssignment_3(), "rule__Compartment__ShapeAssignment_3");
					put(grammarAccess.getCompartmentRectangleAccess().getLayoutAssignment_2_1(), "rule__CompartmentRectangle__LayoutAssignment_2_1");
					put(grammarAccess.getCompartmentRectangleAccess().getIdAssignment_2_2(), "rule__CompartmentRectangle__IdAssignment_2_2");
					put(grammarAccess.getCompartmentRoundedRectangleAccess().getLayoutAssignment_2_1(), "rule__CompartmentRoundedRectangle__LayoutAssignment_2_1");
					put(grammarAccess.getCompartmentRoundedRectangleAccess().getIdAssignment_2_2(), "rule__CompartmentRoundedRectangle__IdAssignment_2_2");
					put(grammarAccess.getCompartmentPolygonAccess().getLayoutAssignment_2_1(), "rule__CompartmentPolygon__LayoutAssignment_2_1");
					put(grammarAccess.getCompartmentPolygonAccess().getIdAssignment_2_2(), "rule__CompartmentPolygon__IdAssignment_2_2");
					put(grammarAccess.getCompartmentEllipseAccess().getLayoutAssignment_2_1(), "rule__CompartmentEllipse__LayoutAssignment_2_1");
					put(grammarAccess.getCompartmentEllipseAccess().getIdAssignment_2_2(), "rule__CompartmentEllipse__IdAssignment_2_2");
					put(grammarAccess.getDescriptionAccess().getStyleAssignment_1_1(), "rule__Description__StyleAssignment_1_1");
					put(grammarAccess.getDescriptionAccess().getHAlignAssignment_1_3_2_2(), "rule__Description__HAlignAssignment_1_3_2_2");
					put(grammarAccess.getDescriptionAccess().getVAlignAssignment_1_3_2_6(), "rule__Description__VAlignAssignment_1_3_2_6");
					put(grammarAccess.getDescriptionAccess().getBodyAssignment_1_4(), "rule__Description__BodyAssignment_1_4");
					put(grammarAccess.getShapeLayoutAccess().getMinwidthAssignment_1_0_4(), "rule__ShapeLayout__MinwidthAssignment_1_0_4");
					put(grammarAccess.getShapeLayoutAccess().getMinheightAssignment_1_0_8(), "rule__ShapeLayout__MinheightAssignment_1_0_8");
					put(grammarAccess.getShapeLayoutAccess().getMaxwidthAssignment_1_1_4(), "rule__ShapeLayout__MaxwidthAssignment_1_1_4");
					put(grammarAccess.getShapeLayoutAccess().getMaxheightAssignment_1_1_8(), "rule__ShapeLayout__MaxheightAssignment_1_1_8");
					put(grammarAccess.getShapeLayoutAccess().getStretchHAssignment_1_2_4(), "rule__ShapeLayout__StretchHAssignment_1_2_4");
					put(grammarAccess.getShapeLayoutAccess().getStretchVAssignment_1_2_8(), "rule__ShapeLayout__StretchVAssignment_1_2_8");
					put(grammarAccess.getShapeLayoutAccess().getProportionalAssignment_1_3_2(), "rule__ShapeLayout__ProportionalAssignment_1_3_2");
					put(grammarAccess.getRectangleEllipseLayoutAccess().getCommonAssignment_1_0(), "rule__RectangleEllipseLayout__CommonAssignment_1_0");
					put(grammarAccess.getRectangleEllipseLayoutAccess().getLayoutAssignment_1_1(), "rule__RectangleEllipseLayout__LayoutAssignment_1_1");
					put(grammarAccess.getLineLayoutAccess().getPointAssignment_1_0(), "rule__LineLayout__PointAssignment_1_0");
					put(grammarAccess.getLineLayoutAccess().getPointAssignment_1_1(), "rule__LineLayout__PointAssignment_1_1");
					put(grammarAccess.getLineLayoutAccess().getLayoutAssignment_1_2(), "rule__LineLayout__LayoutAssignment_1_2");
					put(grammarAccess.getPolyLineLayoutAccess().getPointAssignment_1_0(), "rule__PolyLineLayout__PointAssignment_1_0");
					put(grammarAccess.getPolyLineLayoutAccess().getPointAssignment_1_1(), "rule__PolyLineLayout__PointAssignment_1_1");
					put(grammarAccess.getPolyLineLayoutAccess().getLayoutAssignment_1_2(), "rule__PolyLineLayout__LayoutAssignment_1_2");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getCommonAssignment_1_0(), "rule__RoundedRectangleLayout__CommonAssignment_1_0");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getCurveWidthAssignment_1_1_4(), "rule__RoundedRectangleLayout__CurveWidthAssignment_1_1_4");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getCurveHeightAssignment_1_1_8(), "rule__RoundedRectangleLayout__CurveHeightAssignment_1_1_8");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getLayoutAssignment_1_2(), "rule__RoundedRectangleLayout__LayoutAssignment_1_2");
					put(grammarAccess.getTextLayoutAccess().getCommonAssignment_1_0(), "rule__TextLayout__CommonAssignment_1_0");
					put(grammarAccess.getTextLayoutAccess().getHAlignAssignment_1_1_2_2(), "rule__TextLayout__HAlignAssignment_1_1_2_2");
					put(grammarAccess.getTextLayoutAccess().getVAlignAssignment_1_1_2_6(), "rule__TextLayout__VAlignAssignment_1_1_2_6");
					put(grammarAccess.getTextLayoutAccess().getLayoutAssignment_1_2(), "rule__TextLayout__LayoutAssignment_1_2");
					put(grammarAccess.getCommonLayoutAccess().getXcorAssignment_1_0_4(), "rule__CommonLayout__XcorAssignment_1_0_4");
					put(grammarAccess.getCommonLayoutAccess().getYcorAssignment_1_0_8(), "rule__CommonLayout__YcorAssignment_1_0_8");
					put(grammarAccess.getCommonLayoutAccess().getWidthAssignment_1_1_4(), "rule__CommonLayout__WidthAssignment_1_1_4");
					put(grammarAccess.getCommonLayoutAccess().getHeigthAssignment_1_1_8(), "rule__CommonLayout__HeigthAssignment_1_1_8");
					put(grammarAccess.getTextBodyAccess().getValueAssignment_3(), "rule__TextBody__ValueAssignment_3");
					put(grammarAccess.getPointAccess().getXcorAssignment_1_4(), "rule__Point__XcorAssignment_1_4");
					put(grammarAccess.getPointAccess().getYcorAssignment_1_8(), "rule__Point__YcorAssignment_1_8");
					put(grammarAccess.getPointAccess().getCurveBeforeAssignment_1_9_3(), "rule__Point__CurveBeforeAssignment_1_9_3");
					put(grammarAccess.getPointAccess().getCurveAfterAssignment_1_9_7(), "rule__Point__CurveAfterAssignment_1_9_7");
					put(grammarAccess.getCompartmentInfoAccess().getUnorderedGroup_2(), "rule__CompartmentInfo__UnorderedGroup_2");
					put(grammarAccess.getShapeLayoutAccess().getUnorderedGroup_1(), "rule__ShapeLayout__UnorderedGroup_1");
					put(grammarAccess.getRectangleEllipseLayoutAccess().getUnorderedGroup_1(), "rule__RectangleEllipseLayout__UnorderedGroup_1");
					put(grammarAccess.getRoundedRectangleLayoutAccess().getUnorderedGroup_1(), "rule__RoundedRectangleLayout__UnorderedGroup_1");
					put(grammarAccess.getTextLayoutAccess().getUnorderedGroup_1(), "rule__TextLayout__UnorderedGroup_1");
					put(grammarAccess.getCommonLayoutAccess().getUnorderedGroup_1(), "rule__CommonLayout__UnorderedGroup_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.eclipselabs.spray.shapes.ui.contentassist.antlr.internal.InternalShapeParser typedParser = (org.eclipselabs.spray.shapes.ui.contentassist.antlr.internal.InternalShapeParser) parser;
			typedParser.entryRuleShapeContainer();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public ShapeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ShapeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
