/*
 * generated by Xtext
 */
package org.eclipselabs.spray.shapes.ui.contentassist

import org.eclipselabs.spray.shapes.ui.contentassist.AbstractShapeProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ShapeProposalProvider extends AbstractShapeProposalProvider {
}
